### ISSUE TITLE
Can I deploy to Heroku or other similar service?

### ISSUE THREAD

**Issue by nickeblewis** [lvarayut/relay-fullstack#7]
Having executed the command line:

$ npm run deploy

How can I push the build up to a service such as Heroku? or similar service?

**Comment by lvarayut** [comment]
Relay Fullstack doesn't provide any specific command for deploying on particular services. Basically, you could follow a guide of that service in order to deploy it. For example, in Heroku, you will need to create a `Procfile` which is included the exact command you want to run, could be as same as `npm run deploy`.

**Comment by nickeblewis** [comment]
Thanks I will try that.

**Comment by lvarayut** [comment]
No problem :)

**Comment by lvarayut** [comment]
Now, Relay Fullstack suuports deploying on Heroku. Please refer to [Heroku deployment](https://github.com/lvarayut/relay-fullstack#heroku) section.
