### ISSUE TITLE
HMR not working for variables.scss

### ISSUE THREAD

**Issue by BlakeBrown** [lvarayut/relay-fullstack#80]
Quick question! Disclaimer: Noob to webpack & HMR

If I change colours in say App.scss:

```
.greeting {
  background-color: $blue;
}
```

to

```
.greeting {
  background-color: $black;
}
```

the app will reload no problem. However if I make changes in variables.scss, say:
`$white: #FFFFFF;`
to
`$white: #EEE;`

... then the app will fail to reload. Is there any explanation for this?

**Comment by lvarayut** [comment]
Hey @BlakeBrown, thanks for your question. It's because the `variables.scss` has never been imported and used in any component. On the other hand, `App.scss` has been imported and used in [AppComponent.js](https://github.com/lvarayut/relay-fullstack/blob/ba98462ecb3c57e9b24670f5bb5ad81521048818/client/components/App/App.scss). That's why HMR can detect any changes from `App.scss`

**Comment by BlakeBrown** [comment]
@lvarayut thanks so much for getting back to me! I guess it's a little bit of a "gotcha" that nested imports don't cause reloads, but I guess you can always restart the server if you need to.

Loving this starter kit so far, thanks a lot! :)

**Comment by lvarayut** [comment]
You're very welcome :), glad that you love Relay Fullstack.I'm going to close this issue for now. Please feel free to continue the discussion here if you had more question!
